DROP TABLE IF EXISTS TRANSACTION;  
CREATE TABLE TRANSACTION (  
TRANSACTION_ID INT PRIMARY KEY,  
CUSTOMER_ID INT NOT NULL,  
CUSTOMER_NAME VARCHAR(50),
TRANSACTION_AMOUNT DECIMAL(10,2),
TRANSACTION_DATE DATE 
);
  